
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service-pedidos
  namespace: pedidos-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos-api
  template:
    metadata:
      labels:
        app: pedidos-api
    spec:
      containers:
      - name: pedidos-api
        image: usuario/pedidos:v1.1.0 # <-- Versionamiento Semántico SemVer (¡No uses latest!)
        ports:
        - containerPort: 8080
        # ADAPTADORES DE SALUD EXIGIDOS POR TU PRÁCTICA:
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
