apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service-pedidos
  namespace: pedidos-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos-api
  template:
    metadata:
      labels:
        app: pedidos-api
    spec:
      containers:
      - name: pedidos-api
        image: an7hony16/pedidos-api:v1.1.76a3aef
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: DATABASE_URL
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: CLOUDINARY_API_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: JWT_SECRET
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: FRONTEND_URL
        - name: PASARELA_API_URL
          valueFrom:
            secretKeyRef:
              name: supabase-db-secrets
              key: PASARELA_API_URL
        - name: OTEL_SERVICE_NAME
          value: "pedidos-api"
        - name: OTEL_LOG_LEVEL
          value: "debug"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
